# Generated by Django 5.0.1 on 2024-01-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolutioapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='shipped',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
