# Generated by Django 5.0.1 on 2024-01-25 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evolutioapi', '0003_product_alter_order_reference_deliveryproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
